name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    defaults:
      run:
        working-directory: glyphspace-main

    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: 🟢 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 25

      - name: 📦 Install dependencies
        run: npm install

      - name: 🛠️ Build Angular app
        run: npm run build -- --base-href=/glyphspace-main_28-08/ --configuration production

      - name: 📄 Create .nojekyll file
        run: echo > dist/glyphspace/browser/.nojekyll

      - name: 🏷️ Write build timestamp
        run: echo "$(date -u +%s)" > dist/glyphspace/browser/build-timestamp.txt

      - name: 🚀 Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./glyphspace-main/dist/glyphspace/browser/
          publish_branch: gh-pages
          enable_jekyll: false
